services:
  cocktails_db:
    image: postgres
    restart: always
    env_file: ./.env    
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - 5432:5432

volumes:
  data: